# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/photos/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Item')),
            ],
        ),
    ]
