# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=1, upload_to='media/images/photos/'),
            preserve_default=False,
        ),
    ]
